### ISSUE TITLE
[Twig_Error_Syntax]   Unknown "render_type" function in "layout.console.twig" at line 2.

### ISSUE THREAD

**Issue by ibasaw** [raulfraile/LadybugBundle#76]
sf 2.8, in console command if i do a ld, got this error now:

    [Twig_Error_Syntax]
      Unknown "render_type" function in "layout.console.twig" at line 2.

**Comment by witzkito** [comment]
Same in sf 2.7 and 2.6. Try various versions in composer.json. I could not make it work any more

**Comment by jdeniau** [comment]
The v1.0.12 version of labybug (not the bundle) is bugged. 
Before https://github.com/raulfraile/ladybug/pull/75 is merged, you can add this in your `composer.json` file:
```
"raulfraile/ladybug": "^1.0.11,!=1.0.12",
```

**Comment by ibasaw** [comment]
thanks, solved !

**Comment by witzkito** [comment]
Thanks!!
