### ISSUE TITLE
Attempted to load class "Null" from namespace "Ladybug\Type".

### ISSUE THREAD

**Issue by arcovoltaico** [raulfraile/LadybugBundle#77]
After running a full composer update my SF is 2.8.1
and LadyBug version is  "v1.0.13".

Now executing ladybug_dump('hi'); throws this error:

Attempted to load class "Null" from namespace "Ladybug\Type".
Did you forget a "use" statement for e.g. "Twig_Cache_Null", "Twig_Node_Expression_Test_Null", "Zend\Filter\Null" or "Symfony\Component\Validator\Constraints\Null"?

I already cleared the cache folder.... Any idea? Thanks a lot !

**Comment by tobemedia** [comment]
I think it´s a problem caused by PHP 7 and it´s class name changes.
Latest version of raulfraile/ladybug should be used
see: https://github.com/raulfraile/ladybug/pull/72
