### ISSUE TITLE
Bundle Maintenance + Symfony3 (and Php7) support.

### ISSUE THREAD

**Issue by giovkanata** [raulfraile/LadybugBundle#79]
@raulfraile there are PR like https://github.com/raulfraile/LadybugBundle/pull/74 and https://github.com/raulfraile/LadybugBundle/pull/71 pending from months.
In the case you can't continue to maintain this bundle do you think it is possible to add some collaborator?
PS: Do anyone knows (@TomasVotruba, @draco1989, @pulzarraider) if there is some fork already updated for Symfony3 + php7?

**Comment by TomasVotruba** [comment]
I have no idea. This package looks abbandobed.

**Comment by draco1989** [comment]
I don't know if there is any fork being updated, sorry. I'm not using it anymore. 

But I think @raulfraile should add some collaborators as well and not let the package die.

**Comment by ibasaw** [comment]
ping @raulfraile

**Comment by tobemedia** [comment]
@ping. symfony 3 (2.7, 2.8) compatibility would be great

**Comment by ibasaw** [comment]
news ?

**Comment by giovkanata** [comment]
3 months without a reply from @raulfraile it's not a good sign.

**Comment by giovkanata** [comment]
closed due to abandoned of this library by the maintainer.
